meta_product_name: "Destination Matcher"
meta_title: "Search by budget and find the best destination for your next vacation."
meta_description: "Search by budget and find the best destination"
meta_image: "image_for_meta_image.jpg"                       # should exist in `app/assets/images/`
